// Load environment variables from .env file
require('dotenv').config();

module.exports = {
  apps: [
    // Production apps
    {
      name: 'coral-backend',
      script: 'src/server.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        HOST: 'localhost',
        // Database Configuration
        MYSQL_USER: process.env.MYSQL_USER,
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
        MYSQL_DATABASE: process.env.MYSQL_DATABASE,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        // JWT Configuration
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
        // Other environment variables
        FRONTEND_URL: process.env.FRONTEND_URL,
        SMTP_HOST: process.env.SMTP_HOST,
        SMTP_PORT: process.env.SMTP_PORT,
        SMTP_USER: process.env.SMTP_USER,
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: process.env.SMTP_FROM,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        TWILIO_WHATSAPP_NUMBER: process.env.TWILIO_WHATSAPP_NUMBER,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE,
        ALLOWED_FILE_TYPES: process.env.ALLOWED_FILE_TYPES,
        ADMIN_EMAIL: process.env.ADMIN_EMAIL,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        ADMIN_NAME: process.env.ADMIN_NAME,
        BACKUPS: process.env.BACKUPS,
        BACKUP_RETENTION_DAYS: process.env.BACKUP_RETENTION_DAYS,
        BACKUP_SCHEDULE_TIME: process.env.BACKUP_SCHEDULE_TIME,
        BACKUP_MONITOR_SCHEDULE: process.env.BACKUP_MONITOR_SCHEDULE,
        BACKUP_MAX_AGE_HOURS: process.env.BACKUP_MAX_AGE_HOURS
      },
      error_file: 'logs/err.log',
      out_file: 'logs/out.log',
      log_file: 'logs/combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
    },
    {
      name: 'coral-notification-worker',
      script: 'src/workers/notificationWorker.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        HOST: 'localhost',
        // Database Configuration
        MYSQL_USER: process.env.MYSQL_USER,
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
        MYSQL_DATABASE: process.env.MYSQL_DATABASE,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        // JWT Configuration
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
        // Other environment variables
        FRONTEND_URL: process.env.FRONTEND_URL,
        SMTP_HOST: process.env.SMTP_HOST,
        SMTP_PORT: process.env.SMTP_PORT,
        SMTP_USER: process.env.SMTP_USER,
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: process.env.SMTP_FROM,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        TWILIO_WHATSAPP_NUMBER: process.env.TWILIO_WHATSAPP_NUMBER,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE,
        ALLOWED_FILE_TYPES: process.env.ALLOWED_FILE_TYPES,
        ADMIN_EMAIL: process.env.ADMIN_EMAIL,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        ADMIN_NAME: process.env.ADMIN_NAME,
        BACKUPS: process.env.BACKUPS,
        BACKUP_RETENTION_DAYS: process.env.BACKUP_RETENTION_DAYS,
        BACKUP_SCHEDULE_TIME: process.env.BACKUP_SCHEDULE_TIME,
        BACKUP_MONITOR_SCHEDULE: process.env.BACKUP_MONITOR_SCHEDULE,
        BACKUP_MAX_AGE_HOURS: process.env.BACKUP_MAX_AGE_HOURS
      },
      error_file: 'logs/worker-err.log',
      out_file: 'logs/worker-out.log',
      log_file: 'logs/worker-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
    },
    {
      name: 'coral-backup-worker',
      script: 'src/workers/backupWorker.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        HOST: 'localhost',
        // Database Configuration
        MYSQL_USER: process.env.MYSQL_USER,
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
        MYSQL_DATABASE: process.env.MYSQL_DATABASE,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        // JWT Configuration
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
        // Other environment variables
        FRONTEND_URL: process.env.FRONTEND_URL,
        SMTP_HOST: process.env.SMTP_HOST,
        SMTP_PORT: process.env.SMTP_PORT,
        SMTP_USER: process.env.SMTP_USER,
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: process.env.SMTP_FROM,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        TWILIO_WHATSAPP_NUMBER: process.env.TWILIO_WHATSAPP_NUMBER,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE,
        ALLOWED_FILE_TYPES: process.env.ALLOWED_FILE_TYPES,
        ADMIN_EMAIL: process.env.ADMIN_EMAIL,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        ADMIN_NAME: process.env.ADMIN_NAME,
        BACKUPS: process.env.BACKUPS,
        BACKUP_RETENTION_DAYS: process.env.BACKUP_RETENTION_DAYS,
        BACKUP_SCHEDULE_TIME: process.env.BACKUP_SCHEDULE_TIME,
        BACKUP_MONITOR_SCHEDULE: process.env.BACKUP_MONITOR_SCHEDULE,
        BACKUP_MAX_AGE_HOURS: process.env.BACKUP_MAX_AGE_HOURS
      },
      error_file: 'logs/backup-err.log',
      out_file: 'logs/backup-out.log',
      log_file: 'logs/backup-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
    },
    
    // Development apps
    {
      name: 'dev-coral-backend',
      script: 'src/server.js',
      instances: 1,
      autorestart: true,
      watch: true,
      ignore_watch: ["logs", "node_modules", ".git", "uploads"],
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 5001,
        HOST: 'localhost',
        // Database Configuration
        MYSQL_USER: process.env.MYSQL_USER,
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
        MYSQL_DATABASE: process.env.MYSQL_DATABASE,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        // JWT Configuration
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
        // Other environment variables
        FRONTEND_URL: process.env.FRONTEND_URL,
        SMTP_HOST: process.env.SMTP_HOST,
        SMTP_PORT: process.env.SMTP_PORT,
        SMTP_USER: process.env.SMTP_USER,
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: process.env.SMTP_FROM,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        TWILIO_WHATSAPP_NUMBER: process.env.TWILIO_WHATSAPP_NUMBER,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE,
        ALLOWED_FILE_TYPES: process.env.ALLOWED_FILE_TYPES,
        ADMIN_EMAIL: process.env.ADMIN_EMAIL,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        ADMIN_NAME: process.env.ADMIN_NAME,
        BACKUPS: process.env.BACKUPS,
        BACKUP_RETENTION_DAYS: process.env.BACKUP_RETENTION_DAYS,
        BACKUP_SCHEDULE_TIME: process.env.BACKUP_SCHEDULE_TIME,
        BACKUP_MONITOR_SCHEDULE: process.env.BACKUP_MONITOR_SCHEDULE,
        BACKUP_MAX_AGE_HOURS: process.env.BACKUP_MAX_AGE_HOURS
      },
      error_file: 'logs/dev-err.log',
      out_file: 'logs/dev-out.log',
      log_file: 'logs/dev-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
    },
    {
      name: 'dev-coral-notification-worker',
      script: 'src/workers/notificationWorker.js',
      instances: 1,
      autorestart: true,
      watch: true,
      ignore_watch: ["logs", "node_modules", ".git", "uploads"],
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 5001,
        HOST: 'localhost',
        // Database Configuration
        MYSQL_USER: process.env.MYSQL_USER,
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
        MYSQL_DATABASE: process.env.MYSQL_DATABASE,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        // JWT Configuration
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
        // Other environment variables
        FRONTEND_URL: process.env.FRONTEND_URL,
        SMTP_HOST: process.env.SMTP_HOST,
        SMTP_PORT: process.env.SMTP_PORT,
        SMTP_USER: process.env.SMTP_USER,
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: process.env.SMTP_FROM,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        TWILIO_WHATSAPP_NUMBER: process.env.TWILIO_WHATSAPP_NUMBER,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE,
        ALLOWED_FILE_TYPES: process.env.ALLOWED_FILE_TYPES,
        ADMIN_EMAIL: process.env.ADMIN_EMAIL,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        ADMIN_NAME: process.env.ADMIN_NAME,
        BACKUPS: process.env.BACKUPS,
        BACKUP_RETENTION_DAYS: process.env.BACKUP_RETENTION_DAYS,
        BACKUP_SCHEDULE_TIME: process.env.BACKUP_SCHEDULE_TIME,
        BACKUP_MONITOR_SCHEDULE: process.env.BACKUP_MONITOR_SCHEDULE,
        BACKUP_MAX_AGE_HOURS: process.env.BACKUP_MAX_AGE_HOURS
      },
      error_file: 'logs/dev-worker-err.log',
      out_file: 'logs/dev-worker-out.log',
      log_file: 'logs/dev-worker-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
    },
    {
      name: 'dev-coral-backup-worker',
      script: 'src/workers/backupWorker.js',
      instances: 1,
      autorestart: true,
      watch: true,
      ignore_watch: ["logs", "node_modules", ".git", "uploads"],
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 5001,
        HOST: 'localhost',
        // Database Configuration
        MYSQL_USER: process.env.MYSQL_USER,
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
        MYSQL_DATABASE: process.env.MYSQL_DATABASE,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        // JWT Configuration
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
        // Other environment variables
        FRONTEND_URL: process.env.FRONTEND_URL,
        SMTP_HOST: process.env.SMTP_HOST,
        SMTP_PORT: process.env.SMTP_PORT,
        SMTP_USER: process.env.SMTP_USER,
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: process.env.SMTP_FROM,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        TWILIO_WHATSAPP_NUMBER: process.env.TWILIO_WHATSAPP_NUMBER,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE,
        ALLOWED_FILE_TYPES: process.env.ALLOWED_FILE_TYPES,
        ADMIN_EMAIL: process.env.ADMIN_EMAIL,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        ADMIN_NAME: process.env.ADMIN_NAME,
        BACKUPS: process.env.BACKUPS,
        BACKUP_RETENTION_DAYS: process.env.BACKUP_RETENTION_DAYS,
        BACKUP_SCHEDULE_TIME: process.env.BACKUP_SCHEDULE_TIME,
        BACKUP_MONITOR_SCHEDULE: process.env.BACKUP_MONITOR_SCHEDULE,
        BACKUP_MAX_AGE_HOURS: process.env.BACKUP_MAX_AGE_HOURS
      },
      error_file: 'logs/dev-backup-err.log',
      out_file: 'logs/dev-backup-out.log',
      log_file: 'logs/dev-backup-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
    }
  ]
};
